env:
  browser: true
  es2021: true
extends:
  - standard
  - plugin:react/recommended
  - next/core-web-vitals
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  no-unused-vars: warn

overrides:
  - files: ['/home/yura/ooscca-fe/src/app/terms/page.js']
    rules:
      quotes: ["error", "single", {"avoidEscape": true, "allowTemplateLiterals": true}]
      jsx-quotes: ["error", "prefer-double"]
